export const MOVIE_INFORMATION_ACTION_TYPES = {
  GET_MORE_LIKE_THIS_STARTED: "GET_MORE_LIKE_THIS_STARTED",
  GET_MORE_LIKE_THIS_SUCCESS: "GET_MORE_LIKE_THIS_SUCCESS",
  GET_MORE_LIKE_THIS_ERROR: "GET_MORE_LIKE_THIS_ERROR",
  SET_MORE_INFO_MOVIE: "SET_MORE_INFO_MOVIE",
  OPEN_MORE_INFO: "OPEN_MORE_INFO",
  CLOSE_MORE_INFO: "CLOSE_MORE_INFO",
};
