export const REGIONS = [
  "",
  "Afghanistan",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea (Republic of Korea)",
  "South Sudan",
  "Spain",
  "Sri Lanka (Ceylon)",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria (Syrian Arab Republic)",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau Islands",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "U.S. Virgin Islands (St. Croix, St. John, St. Thomas)",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom (Great Britain)",
  "United States",
  "United States Minor Outlying Islands (Baker Island, Midway Atoll, Wake Island)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu (New Hebrides)",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const STEPS = {
  TERMS_AND_CONDITIONS: "Terms and Conditions",
  PERSONAL_INFORMATION: "Personal Information",
  PAYMENT_INFORMATION: "Payment Information",
};
