const HOME_SCREEN_ACTION_TYPES = {
  GET_MOVIES_LIST_STARTED: "GET_MOVIES_LIST_STARTED",
  GET_MOVIES_LIST_ERROR: "GET_MOVIES_LIST_ERROR",
  GET_MOVIES_LIST_SUCCESS: "GET_MOVIES_LIST_SUCCESS",
  GET_RANDOM_MOVIE_STARTED: "GET_RANDOM_MOVIE_STARTED",
  GET_RANDOM_MOVIE_ERROR: "GET_RANDOM_MOVIE_ERROR",
  GET_RANDOM_MOVIE_SUCCESS: "GET_RANDOM_MOVIE_SUCCESS",
  GET_MY_LIST_STARTED: "GET_MY_LIST_STARTED",
  GET_MY_LIST_SUCCESS: "GET_MY_LIST_SUCCESS",
  GET_MY_LIST_ERROR: "GET_MY_LIST_ERROR",
  ADD_TO_MY_LIST_SUCCESS: "ADD_TO_MY_LIST_SUCCESS",
  ADD_TO_MY_LIST_ERROR: "ADD_TO_MY_LIST_ERROR",
  DELETE_FROM_MY_LIST_SUCCESS: " DELETE_FROM_MY_LIST_SUCCESS",
  DELETE_FROM_MY_LIST_ERROR: " DELETE_FROM_MY_LIST_ERROR",
};

export default HOME_SCREEN_ACTION_TYPES;
