const SIGNUP_ACTION_TYPES = {
  CHANGE_ACTIVE_STEP: "CHANGE_ACTIVE_STEP",
  CHANGE_TERMS_AND_CONDITION_CHECKBOX: "CHANGE_TERMS_AND_CONDITION_CHECKBOX",
  CHANGE_STEP_STATUS: "CHANGE_STEP_STATUS",
  CHANGE_INPUT_FIELD: "CHANGE_INPUT_FIELD",
  UPDATE_SIGN_UP_PROGRESS: "UPDATE_SIGN_UP_PROGRESS",
  VERIFY_USER_EXISTS_STARTED: "VERIFY_USER_EXISTS",
  VERIFY_USER_EXISTS_SUCCESS: "VERIFY_USER_SUCCESS",
  VERIFY_USER_EXISTS_ERROR: "VERIFY_USER_ERROR",
  CREATE_ACCOUNT_STARTED: "CREATE_ACCOUNT_STARTED",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_ERROR: "CREATE_ACCOUNT_ERROR",
  RESET_CREATE_ACCOUT_ERROR: "RESET_CREATE_ACCOUT_ERROR",
  RESET_SIGN_UP: "RESET_SIGN_UP",
};

export default SIGNUP_ACTION_TYPES;
