const SIGNUP_ACTION_TYPES = {
  CHANGE_ACTIVE_STEP: "CHANGE_ACTIVE_STEP",
  CHANGE_TERMS_AND_CONDITION_CHECKBOX: "CHANGE_TERMS_AND_CONDITION_CHECKBOX",
  CHANGE_STEP_STATUS: "CHANGE_STEP_STATUS",
  CHANGE_INPUT_FIELD: "CHANGE_INPUT_FIELD",
  UPDATE_SIGN_UP_PROGRESS: "UPDATE_SIGN_UP_PROGRESS",
  VERIFY_USER_EXISTS_STARTED: "VERIFY_USER_EXISTS",
  VERIFY_USER_EXISTS_SUCCESS: "VERIFY_USER_SUCCESS",
  VERIFY_USER_EXISTS_ERROR: "VERIFY_USER_ERROR",
};

export default SIGNUP_ACTION_TYPES;
