const SIGNUP_ACTION_TYPES = {
  CHANGE_ACTIVE_STEP: "CHANGE_ACTIVE_STEP",
  CHANGE_TERMS_AND_CONDITION_CHECKBOX: "CHANGE_TERMS_AND_CONDITION_CHECKBOX",
  CHANGE_STEP_STATUS: "CHANGE_STEP_STATUS",
  CHANGE_INPUT_FIELD: "CHANGE_INPUT_FIELD",
  UPDATE_SIGN_UP_PROGRESS: "UPDATE_SIGN_UP_PROGRESS",
};

export default SIGNUP_ACTION_TYPES;
