const MEDIA_PLAYER_ACTION_TYPES = {
  OPEN_MEDIA_PLAYER: "OPEN_MEDIA_PLAYER",
  CLOSE_MEDIA_PLAYER: "CLOSE_MEDIA_PLAYER",
};

const USER_ACTION_TYPES = {
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",
  AUTHENTICATE_USER_STARTED: "AUTHENTICATE_USER_STARTED",
  AUTHENTICATE_USER_ERROR: "AUTHENTICATE_USER_STARTED",
  AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  LOGIN_USER_STARTED: "LOGIN_USER_STARTED",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
};

const ALERT_ACTION_TYPES = {
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
};

const GLOBAL_ACTIONS_TYPES = {
  MEDIA_PLAYER_ACTION_TYPES,
  USER_ACTION_TYPES,
  ALERT_ACTION_TYPES,
};

export default GLOBAL_ACTIONS_TYPES;
